# Generated by Django 4.0.4 on 2022-07-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_id_alter_message_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_picture',
            field=models.ImageField(blank=True, upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='Profile_images/'),
        ),
    ]
