# Generated by Django 3.2.12 on 2022-03-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220324_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_picture',
            field=models.ImageField(default='kindpng_4517876.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='kindpng_4517876.png', upload_to=''),
        ),
    ]
