# Generated by Django 3.2.12 on 2022-03-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='kindpng_4517876.png', null=True, upload_to=''),
        ),
    ]
