# Generated by Django 3.2.12 on 2022-03-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='kindpng_4517876.png', upload_to=''),
        ),
    ]
