# Generated by Django 3.2.12 on 2022-03-30 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0017_auto_20220330_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentor',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentor',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
