# Generated by Django 3.2.12 on 2022-04-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_comment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
