# Generated by Django 3.2.12 on 2022-04-21 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_alter_message_reciever'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read']},
        ),
    ]
